export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  FLOW_CONFLICT: "FLOW_CONFLICT",
  OPEN_PLAN_EXISTS: "OPEN_PLAN_EXISTS",
  PLAN_CONTENT_CHANGED: "PLAN_CONTENT_CHANGED",
  ALREADY_PROCESSED: "ALREADY_PROCESSED",
  ARCHIVE_NOT_READY: "ARCHIVE_NOT_READY"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
